python3 main.py 0
python3 cf_output_with_ref.py 0
python3 main.py 1
python3 cf_output_with_ref.py 1
python3 main.py 2
python3 cf_output_with_ref.py 2
python3 main.py 3
python3 cf_output_with_ref.py 3
python3 main.py 4
python3 cf_output_with_ref.py 4
python3 main.py 5
python3 cf_output_with_ref.py 5
python3 main.py 6
python3 cf_output_with_ref.py 6